# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_pointhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointhistory',
            old_name='message',
            new_name='content',
        ),
    ]
