# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 08:08
from __future__ import unicode_literals

from django.db import migrations
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20170408_0547'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', member.models.UserManager()),
            ],
        ),
    ]
